### ISSUE TITLE
Evitar que pete cuando hay algún error (bloqueo, por ejemplo)

### ISSUE THREAD

**Issue by JJ** [JJ/denotas-bot#6]
Por ejemplo, este:

```
error: Uncaught (in promise) Error: 403
Forbidden: bot was blocked by the user
          throw new Error(`${error_code}\n${description}`);
```

**Comment by JJ** [comment]
También hay este error:

```
error: Uncaught (in promise) Error: 400
Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
          throw new Error(`${error_code}\n${description}`);
                ^
    at https://deno.land/x/telegram_bot_api@0.4.0/src/telegram-bot/telegram-bot.ts:213:17
    at async file:///home/jmerelo/Asignaturas/infraestructura-virtual/denotas-bot/main.ts:28:3
```

Aunque este es nuevo, y es cuando se ha añadido parsing con markdown de los mensajes (aunque pensaba que era por cada mensaje)

**Comment by JJ** [comment]
Error cuando el nombre tiene un subrayado: 

```
error: Uncaught (in promise) Error: 400
Bad Request: can't parse entities: Can't find end of Bold entity at byte offset 106
          throw new Error(`${error_code}\n${description}`);
```
